# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-15 04:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appmain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blog',
            name='on_page',
            field=models.BooleanField(default=False),
        ),
    ]
