# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-15 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0002_auto_20161115_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='channel_chosen',
            field=models.CharField(default='default', max_length=1000),
        ),
    ]
