# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-23 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0003_auto_20161115_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='republish',
            field=models.BooleanField(default=False),
        ),
    ]
