# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-03 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0005_css_crawl'),
    ]

    operations = [
        migrations.AddField(
            model_name='css_crawl',
            name='error_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='css_crawl',
            name='exclude_words',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='css_crawl',
            name='include_words',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='css_crawl',
            name='login_pw',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='css_crawl',
            name='login_user',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='css_crawl',
            name='css_selector',
            field=models.CharField(max_length=200),
        ),
    ]
