# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-04 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0006_auto_20161203_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='css_crawl',
            name='default_onpage',
            field=models.BooleanField(default=True),
        ),
    ]
