# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-04 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0007_css_crawl_default_onpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='css_crawl',
            name='include_words',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
