# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-04 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0008_auto_20161204_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='css_crawl',
            name='channel',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='css_crawl',
            name='error_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='css_crawl',
            name='exclude_words',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='css_crawl',
            name='login_pw',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='css_crawl',
            name='login_user',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='css_crawl',
            name='tags',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='css_crawl',
            name='top',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
