# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-13 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0009_auto_20161204_2042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('name_en', models.CharField(max_length=30, unique=True)),
                ('sub_channel', models.CharField(max_length=30, null=True)),
                ('state', models.IntegerField()),
                ('order', models.IntegerField()),
                ('content', models.TextField(max_length=1000)),
                ('top_url', models.URLField(null=True)),
                ('icon', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
