# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-23 14:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appmain', '0012_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='gera',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appmain.Genre'),
        ),
        migrations.AddField(
            model_name='genre',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
